// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Wvn6rX4ihnPJB1kjTxJdwIRe3A6UH6w',
    appId: '1:869389738101:web:208232c5020ab314da983c',
    messagingSenderId: '869389738101',
    projectId: 'flutter-crud-62254',
    authDomain: 'flutter-crud-62254.firebaseapp.com',
    storageBucket: 'flutter-crud-62254.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYY69UaaBrYhfJkMhvCPKcj9bH2VKt4pc',
    appId: '1:869389738101:android:e07c924bdd34b436da983c',
    messagingSenderId: '869389738101',
    projectId: 'flutter-crud-62254',
    storageBucket: 'flutter-crud-62254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZbxNeStxRFOba6Tq6Xx_UkOiE4m6VpKs',
    appId: '1:869389738101:ios:adcfff1dc56a1f67da983c',
    messagingSenderId: '869389738101',
    projectId: 'flutter-crud-62254',
    storageBucket: 'flutter-crud-62254.appspot.com',
    iosBundleId: 'com.example.flutterCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZbxNeStxRFOba6Tq6Xx_UkOiE4m6VpKs',
    appId: '1:869389738101:ios:adcfff1dc56a1f67da983c',
    messagingSenderId: '869389738101',
    projectId: 'flutter-crud-62254',
    storageBucket: 'flutter-crud-62254.appspot.com',
    iosBundleId: 'com.example.flutterCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Wvn6rX4ihnPJB1kjTxJdwIRe3A6UH6w',
    appId: '1:869389738101:web:7b05e59b38829054da983c',
    messagingSenderId: '869389738101',
    projectId: 'flutter-crud-62254',
    authDomain: 'flutter-crud-62254.firebaseapp.com',
    storageBucket: 'flutter-crud-62254.appspot.com',
  );
}
